### ISSUE TITLE
In-line Discussions will not render

### ISSUE THREAD

**Issue by itsbenweeks** [mitodl/salt-ops#107]
Loading discussions in-line does not work on courses that are imported via gitreload.

**Comment by itsbenweeks** [comment]
This may be a red herring due to links directing me off the testing stack. Going to reconfirm.

**Comment by itsbenweeks** [comment]
Okay, just imported into https://dogwood-qa-draft.mitx.mit.edu/courses/DevOps/0.001/2015_Summer/courseware/4695c7a6558c4e839c4bfd2e80ae810b/42fedafb26874e1fa8d0d81c74c2d269/ and it does not work properly.

**Comment by pdpinch** [comment]
This appears to be the corresponding stack trace:

```
Internal Server Error: /courses/DevOps/0.001/2015_Summer/discussion/forum/400f0110accd74a54c908f51a2969c298f288854/inline
Traceback (most recent call last):
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
   return func(*args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
   return view_func(request, *args, **kwargs)
 File "/edx/app/edxapp/edx-platform/lms/djangoapps/django_comment_client/forum/views.py", line 182, in wrapped_view
   return view_func(request, course_key, *args, **kwargs)
 File "/edx/app/edxapp/edx-platform/lms/djangoapps/django_comment_client/forum/views.py", line 196, in inline_discussion
   user_info = cc_user.to_dict()
 File "/edx/app/edxapp/edx-platform/lms/lib/comment_client/models.py", line 60, in to_dict
   self.retrieve()
 File "/edx/app/edxapp/edx-platform/lms/lib/comment_client/models.py", line 65, in retrieve
   self._retrieve(*args, **kwargs)
 File "/edx/app/edxapp/edx-platform/lms/lib/comment_client/user.py", line 132, in _retrieve
   metric_tags=self._metric_tags,
 File "/edx/app/edxapp/edx-platform/lms/lib/comment_client/utils.py", line 85, in perform_request
   timeout=5
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
   response = session.request(method=method, url=url, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
   resp = self.send(prep, **send_kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
   r = adapter.send(request, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
   raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))

```

**Comment by itsbenweeks** [comment]
This seems to be for imported courses. I added a discussion component via studio and it will render at https://dogwood-qa-draft.mitx.mit.edu/courses/DevOps/0.001/2015_Summer/courseware/4695c7a6558c4e839c4bfd2e80ae810b/42fedafb26874e1fa8d0d81c74c2d269/

**Comment by itsbenweeks** [comment]
Also was unable to create a post. Unchecking the (default) `Follow this post` button allowed it to work.

**Comment by blarghmatey** [comment]
This is likely due to the fact that the Mongo forum migration had not yet been run. I ran that migration yesterday so let me know if this continues to be an issue @itsbenweeks

**Comment by itsbenweeks** [comment]
Looks like this still won't load.

**Comment by blarghmatey** [comment]
@itsbenweeks Forum deployments have been fixed and the schema migration has been applied. Let me know if your original issue is still happening.

**Comment by itsbenweeks** [comment]
It looks like this works now, but the previous discussions that I added don't show. This won't be a problem with the upcoming courses, though.

**Comment by pdpinch** [comment]
@itsbenweeks is there more to be done here? Is it working as you expect?

**Comment by itsbenweeks** [comment]
It's working as I expect. That's why I moved it to done.

**Comment by pdpinch** [comment]
Sorry, can you close the issues when they're working, or move them to closed?

Moving to done doesn't close them. We don't really have a step between done and closed. I should remove that column from the board.
