### ISSUE TITLE
Sysadmin imports do not work.

### ISSUE THREAD

**Issue by itsbenweeks** [mitodl/salt-ops#108]
From testing on https://dogwood-qa-live.mitx.mit.edu/sysadmin/courses to import https://github.mit.edu/MITx-Studio2LMS/content-mit-0-001-2015_Summer

```
rdir = content-mit-0-001-2015_Summer
Error running git pull: "Cloning into 'content-mit-0-001-2015_Summer'...\nCould not create directory '/var/www/.ssh'.\r\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/dashboard/git_import.py", line 169, in add_repo
    ret_git = cmd_log(cmd, cwd=cwd)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/dashboard/git_import.py", line 61, in cmd_log
    output = subprocess.check_output(cmd, cwd=cwd, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['git', 'clone', u'git@github.mit.edu:MITx-Studio2LMS/content-mit-0-001-2015_Summer.git']' returned non-zero exit status 128
```

**Comment by blarghmatey** [comment]
We're at least getting a different error now.
```
rdir = content-mit-0-001-2015_Summer
Error running git pull: "Cloning into 'content-mit-0-001-2015_Summer'...\nfatal: could not read Username for 'https://github.mit.edu': No such device or address\n"
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/dashboard/git_import.py", line 169, in add_repo
    ret_git = cmd_log(cmd, cwd=cwd)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/dashboard/git_import.py", line 61, in cmd_log
    output = subprocess.check_output(cmd, cwd=cwd, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['git', 'clone', u'https://github.mit.edu/MITx-Studio2LMS/content-mit-0-001-2015_Summer']' returned non-zero exit status 128
```

**Comment by bdero** [comment]
Ben's failed because the host key wasn't setup, and Tobias' export failed because github.mit.edu requires an ssh url.

**Comment by blarghmatey** [comment]
It's working!

**Comment by bdero** [comment]
:+1: :+1: :+1:

**Comment by itsbenweeks** [comment]
Are these keys consistent across all machines? I'm still getting:
```
Error running git pull: "Cloning into 'content-mit-0-001-2015_Summer'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
```
as above. (though abridged here.)

**Comment by blarghmatey** [comment]
This has been verified working on draft and live after the most recent rebuild @itsbenweeks

**Comment by itsbenweeks** [comment]
Awesome! I'll check it out right now, @blarghmatey!

**Comment by itsbenweeks** [comment]
New error now!

```
git clone or pull failed!
rdir = content-mit-0-001-2015_Summer
directory already exists, doing a git pull instead of git clone
Error running git pull: 'Host key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n'
```

**Comment by pdpinch** [comment]
@itsbenweeks which servers and repo were you testing with? 

I successfully loaded the DevOps course on qa-live

git@github.mit.edu:mitx/content-devops-0001.git
https://dogwood-qa-live.mitx.mit.edu/sysadmin/courses

The error you're receiving suggests the server doesn't have the right key, or the repository doesn't have the right user.

I'll test on qa-draft as soon as it's available.

**Comment by itsbenweeks** [comment]
@pdpinch, I've been testing on https://dogwood-qa-live.mitx.mit.edu/sysadmin/courses with the repository at https://github.mit.edu/MITx-Studio2LMS/content-mit-0-001-2015_Summer

**Comment by pdpinch** [comment]
Ok. That just worked for me. 

https://dogwood-qa-live.mitx.mit.edu/sysadmin/courses
git@github.mit.edu:mitx/content-devops-0001.git
