### ISSUE TITLE
Studio home page 500 errors.

### ISSUE THREAD

**Issue by itsbenweeks** [mitodl/salt-ops#110]
For some reason when I try visiting https://studio-dogwood-qa-draft.mitx.mit.edu/home/ for the first time, the system will give me a 500 error after I present my credentials. Reloading one doesn't help, but reloading twice seemed to.

**Comment by pdpinch** [comment]
We seem to still be having problems with mongo connectivity?

`AutoReconnect: not master and slaveOk=false`

```
Internal Server Error: /home/
Traceback (most recent call last):
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
   return func(*args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
   return view_func(request, *args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
   response = view_func(request, *args, **kwargs)
 File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/course.py", line 429, in course_listing
   courses, in_process_course_actions = get_courses_accessible_to_user(request)
 File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/course.py", line 596, in get_courses_accessible_to_user
   courses, in_process_course_actions = _accessible_courses_list(request)
 File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/course.py", line 366, in _accessible_courses_list
   courses = filter(course_filter, modulestore().get_courses())
 File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 90, in inner
   retval = func(field_decorator=strip_key_collection, *args, **kwargs)
 File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 276, in get_courses
   for course in store.get_courses(**kwargs):
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mongodb_proxy.py", line 53, in wrapper
   return func(*args, **kwargs)
 File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/mongo/base.py", line 994, in get_courses
   in course_records
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1149, in next
   if len(self.__data) or self._refresh():
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1081, in _refresh
   self.__codec_options.uuid_representation))
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1023, in __send_message
   self.__compile_re)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pymongo/helpers.py", line 136, in _unpack_response
   raise AutoReconnect(error_object["$err"])
AutoReconnect: not master and slaveOk=false
```

**Comment by blarghmatey** [comment]
This is because I haven't rolled out the latest changes to address these connection areas. I just started it now so it should be more stable by the time you're done with lunch :)

**Comment by blarghmatey** [comment]
After some trial and error the proper read preference configuration has been found!
