### ISSUE TITLE
accounts created via Touchstone collaboration can't access account settings or profile

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#172]
for example:

```
Internal Server Error: /u/a_2@touchstonenetwork.net
Traceback (most recent call last):
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
   return func(*args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
   return view_func(request, *args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
   return func(request, *args, **kwargs)
 File "/edx/app/edxapp/edx-platform/lms/djangoapps/student_profile/views.py", line 43, in learner_profile
   learner_profile_context(request, username, request.user.is_staff)
 File "/edx/app/edxapp/edx-platform/lms/djangoapps/student_profile/views.py", line 69, in learner_profile_context
   account_settings_data = get_account_settings(request, profile_username)
 File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/user_api/helpers.py", line 76, in _wrapped
   raise api_error(msg)
UserAPIInternalError: An unexpected error occurred when calling 'get_account_settings' with arguments '(<WSGIRequest: GET '/u/a_2@touchstonenetwork.net'>, u'a_2@touchstonenetwork.net')' and keyword arguments '{}': NoReverseMatch(u"Reverse for 'accounts_api' with arguments '()' and keyword arguments '{'username': u'a_2@touchstonenetwork.net'}' not found. 1 pattern(s) tried: ['api/user/v1/accounts/(?P<username>[\\\\w.+-]+)$']",)
```

Just a guess, but I think this may have to do with the fact the username doesn't match the e-mail address on these accounts, e.g.

```
    username                                e-mail address
    a_2@touchstonenetwork.net   a@hawklake.com  Peter   Pinch   False
    jamerz_2@touchstonenetwork.net  jamerz@gmail.com    Yechiel Labunskiy   False
    laluna725_1@touchstonenetwork.  laluna725@gmail.com Becky   Zheng   False
    mek.1803_1@touchstonenetwork.n  mek.1803@gmail.com  Teerapat    Jenrungrot  False
    syaguang_1@touchstonenetwork.n  syaguang@126.com    Yaguang Song    False
    utpalrai1996_1@touchstonenetwo  utpalrai1996@gmail.com  UTPAL   RAI False
```

**Comment by pdpinch** [comment]
We removed the links from the theme.
