### ISSUE TITLE
mitx-theme is not compatible with next release

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#207]
Our custom theme was being loaded by edx-platform, but it is causing failures in the app which means that we need to modify it before it can be used with the new release.

Stacktrace:
```
    2017-01-10 15:24:36,389 ERROR 25028 [django.request] base.py:256 - Internal Server Error: /
    Traceback (most recent call last):
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
        response = view_func(request, *args, **kwargs)
      File "/edx/app/edxapp/edx-platform/common/djangoapps/util/cache.py", line 78, in wrapper
        response = view_func(request, *args, **kwargs)
      File "/edx/app/edxapp/edx-platform/lms/djangoapps/branding/views.py", line 90, in index
        return student.views.index(request, user=request.user)
      File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 198, in index
        return render_to_response('index.html', context)
      File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 180, in render_to_response
        return HttpResponse(render_to_string(template_name, dictionary, context_instance, namespace, request), **kwargs)
      File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 170, in render_to_string
        return template.render_unicode(**context_dictionary)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/template.py", line 454, in render_unicode
        as_unicode=True)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 829, in _render
        **_kwargs_for_callable(callable_, data))
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
        _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
        callable_(context, *args, **kwargs)
      File "/tmp/mako_lms/a2b0dda4fba8f36dc7c8a2e63893049c/main.html.py", line 283, in render_body
        runtime._include_file(context, (static.get_template_path('header.html')), _template_uri, online_help_token=online_help_token)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 752, in _include_file
        callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))
      File "/tmp/mako_lms/a2b0dda4fba8f36dc7c8a2e63893049c/header.html.py", line 34, in render_body
        runtime._include_file(context, (static.get_themed_template_path(relative_path='theme-header.html', default_path='navigation.html')), _template_uri, online_help_token=online_help_token)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 748, in _include_file
        template = _lookup_template(context, uri, calling_uri)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 793, in _lookup_template
        return lookup.get_template(uri)
      File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/paths.py", line 74, in get_template
        template = super(DynamicTemplateLookup, self).get_template(get_template_path_with_theme(uri))
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/lookup.py", line 253, in get_template
        return self._load(srcfile, uri)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/lookup.py", line 318, in _load
        **self.template_args)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/template.py", line 322, in __init__
        module = self._compile_from_file(path, filename)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/template.py", line 379, in _compile_from_file
        module = compat.load_module(self.module_id, path)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/compat.py", line 89, in load_module
        return imp.load_source(module_id, path, fp)
      File "/tmp/mako_lms/a2b0dda4fba8f36dc7c8a2e63893049c/mitx-theme/lms/templates/navigation.html.py", line 21, in <module>
        from microsite_configuration.templatetags.microsite import platform_name
    ImportError: No module named templatetags.microsite
```

**Comment by blarghmatey** [comment]
Issue has been resolved as a series of patches on current master if mitodl/mitx-theme
