### ISSUE TITLE
Ficus: Error Enrolling into DevOps Course

### ISSUE THREAD

**Issue by NotoriousMKD** [mitodl/salt-ops#316]
Trying to enroll in the DevOps course on LMS results in an error: 
![screenshot 2017-06-07 12 27 44](https://user-images.githubusercontent.com/8322892/26889611-beb02a38-4b7c-11e7-9cc3-f27e5648addf.png)

https://mitx-qa-next.mitx.mit.edu/courses/course-v1:DevOps+0.001+2015_Summer/about

I haven't had this error happen when enrolling in any other courses.

**Comment by pdpinch** [comment]
I tried importing the course again through the sysadmin panel. I got the following stack trace:

```
Internal Server Error: /sysadmin/courses
Traceback (most recent call last):
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
   return func(*args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
   return self.dispatch(request, *args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
   return bound_func(*args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
   response = view_func(request, *args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
   return func.__get__(self, type(self))(*args2, **kwargs2)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
   return bound_func(*args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
   return view_func(request, *args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
   return func.__get__(self, type(self))(*args2, **kwargs2)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
   return bound_func(*args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
   response = viewfunc(request, *args, **kw)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
   return func.__get__(self, type(self))(*args2, **kwargs2)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
   return bound_func(*args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 158, in inner
   response = func(request, *args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
   return func.__get__(self, type(self))(*args2, **kwargs2)
 File "/edx/app/edxapp/edx-platform/lms/djangoapps/dashboard/sysadmin.py", line 70, in dispatch
   return super(SysadminDashboardView, self).dispatch(*args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
   return handler(request, *args, **kwargs)
 File "/edx/app/edxapp/edx-platform/lms/djangoapps/dashboard/sysadmin.py", line 472, in post
   self.msg += self.get_course_from_git(gitloc, branch)
 File "/edx/app/edxapp/edx-platform/lms/djangoapps/dashboard/sysadmin.py", line 372, in get_course_from_git
   return self.import_mongo_course(gitloc, branch)
 File "/edx/app/edxapp/edx-platform/lms/djangoapps/dashboard/sysadmin.py", line 403, in import_mongo_course
   git_import.add_repo(gitloc, None, branch)
 File "/edx/app/edxapp/edx-platform/lms/djangoapps/dashboard/git_import.py", line 277, in add_repo
   nostatic=not git_import_static)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
   return command.execute(*args, **defaults)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
   output = self.handle(*args, **options)
 File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/management/commands/import.py", line 55, in handle
   seed_permissions_roles(course_id)
 File "/edx/app/edxapp/edx-platform/common/djangoapps/django_comment_common/utils.py", line 42, in seed_permissions_roles
   administrator_role = _save_forum_role(course_key, FORUM_ROLE_ADMINISTRATOR)
 File "/edx/app/edxapp/edx-platform/common/djangoapps/django_comment_common/utils.py", line 30, in _save_forum_role
   role, created = Role.objects.get_or_create(name=name, course_id=course_key)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
   return getattr(self.get_queryset(), name)(*args, **kwargs)
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 405, in get_or_create
   return self.get(**lookup), False
 File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py", line 338, in get
   (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one Role -- it returned 2!
```

**Comment by shaidar** [comment]
This was caused by duplicate roles as specified [here](https://github.mit.edu/mitx-devops/mitx-sysdocs/blob/master/trouble/duplicate_roles.md). Confusing part was that when troubleshooting, the course appears to have multiple course_keys. I was initially looking at `DevOps/0.001/2015_Summer` and didn't see any duplicates, but then tried `course-v1:DevOps+0.001+2015_Summer` as the course_key and came across the duplicate roles.
