### ISSUE TITLE
Ginkgo: NULL course_end_date crashes course about page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#490]
This is an upstream issue in edx-platform, but they never notice because users can't reach the course /about page. 

You can see the 500 error on Residential MITx at https://lms.mitx.mit.edu/courses/course-v1:MITx+16.83r_1+2017_Fall/about

Here is the stack trace:

```
Internal Server Error: /courses/course-v1:MITx+16.83r_1+2017_Fall/about
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/util/cache.py", line 78, in wrapper
    response = view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/views/views.py", line 671, in course_about
    return render_to_response('courseware/course_about.html', context)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 198, in render_to_response
    return HttpResponse(render_to_string(template_name, dictionary, context_instance, namespace, request), **kwargs)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 188, in render_to_string
    return template.render_unicode(**context_dictionary)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/template.py", line 454, in render_unicode
    as_unicode=True)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/mako_lms/dbdb0b7490ee0ca1edd681bf46189227/main.html.py", line 286, in render_body
    __M_writer(filters.decode.utf8(self.body()))
  File "/tmp/mako_lms/dbdb0b7490ee0ca1edd681bf46189227/courseware/course_about.html.py", line 252, in render_body
    course_date_string = course_end_date.strftime('%Y-%m-%dT%H:%M:%S%z')
AttributeError: 'NoneType' object has no attribute 'strftime'
```

**Comment by pdpinch** [comment]
Note that this only appears to be an issue when the course's end date is set to Null, signified by the line `        "end": null, ` in policy.json. 

Newly minted courses without an end date appear to omit that key altogether.

**Comment by pdpinch** [comment]
This was addressed upstream by https://github.com/edx/edx-platform/pull/17263 which should be part of Hawthorn.
